spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: controller
            uri: http://localhost:8081
            predicates:
              - Path=/student/**


  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hb_university
  jpa:
    hibernate:
      ddl-auto: update